### ISSUE TITLE
firebase cloudmessaging native linking error on ios

### ISSUE THREAD

**Issue by Shaboo** [xamarin/GoogleApisForiOSComponents#129]
I am using firebase cloud messaging version (), 
it work in debug mode, but when build for appstore, the following error happen:
Native linking error: truncated fat file. Slice from 4611984 to 6449696 is past end of file with length 5144576 file '/Users/mohammadshaban/Library/Caches/Xamarin/mtbs/builds/HBRS.iOS/7757187b09de98f2bb163c41d580c1ef/obj/iPhone/AppStore/mtouch-cache/FirebaseMessaging' for architecture arm64

**Comment by Shaboo** [comment]
it seams that this component not support arm64 yet, isn't it?

**Comment by SotoiGhost** [comment]
Hi @Shaboo!

Firebase Cloud Messaging it does support **arm64** architecture. You can see it in this [archive][1]. Also, **arm64** arch is in the Firebase Cloud Messaging framework. If you inspect the Firebase Cloud Messaging framework located at **~/username/Library/Caches/XamarinBuildDownload/FCldM-2.0.4/Frameworks/FirebaseMessaging.framework** using `file FirebaseMessaging` command in terminal, you can see the following output:

```
FirebaseMessaging.framework username$ file FirebaseMessaging
FirebaseMessaging: Mach-O universal binary with 4 architectures: [i386:current ar archive] [arm64]
FirebaseMessaging (for architecture i386):	current ar archive
FirebaseMessaging (for architecture armv7):	current ar archive
FirebaseMessaging (for architecture x86_64):	current ar archive
FirebaseMessaging (for architecture arm64):	current ar archive
```

As you can see, **arm64** is presented in the fat library.

I built the app for App Store and everything worked for me. Can you, please, erase the **bin** and **obj** folder from your project and try again?

Thanks in advance!

Greetings,
Israel Soto.

[1]: https://github.com/SotoiGhost/GoogleApisForiOSComponents/blob/new/firebaseioscloudfirestore-0.9.4/Firebase.CloudMessaging/source/Firebase.CloudMessaging/FirebaseCloudMessaging.linkwith.cs#L5

**Comment by Shaboo** [comment]
thanks for your reply,
so, any idea why that error is happened only with me?

**Comment by SotoiGhost** [comment]
I'm not really sure, to be honest. Does removing the folders worked for you? If so, maybe some file was corrupted.

About the PR, we have been a little busy due to internal changes in some teams, as well as, to arrivals of new projects. While the PR is approved, you can build the NuGet package of new versions and reference them locally.

To do so, clone [this fork][1] and switch to `update/firebase-4.8.0` branch. Then, follow these [instructions][2] running the `nuget` target.

Finally, follow this [documentation][3] to learn how to add NuGet packages from your computer.

Best,
Israel Soto.

[1]: https://github.com/SotoiGhost/GoogleApisForiOSComponents
[2]: https://github.com/SotoiGhost/GoogleApisForiOSComponents/tree/update/firebase-4.8.0#building
[3]: https://docs.microsoft.com/en-us/visualstudio/mac/nuget-walkthrough#adding-package-sources

**Comment by Shaboo** [comment]
I did remove everything and that did not work for me, I going to try building the new PR as instructed above and feedback you , if that does not for me, I am going to use "app centre push"
you can close this issue,

your reply and instructions are appreciated,

best regards,

mohammad shaban

**Comment by SotoiGhost** [comment]
@Shaboo Another thing you can try is setting the **Link Behavior** to **Don't link** in project settings. Open Project Setting/iOS Build/Link Behavior and change it. Play with the values, but between each change, erase **bin** and **obj** folders.

**Comment by SotoiGhost** [comment]
Closing this issue now. If something else happens related to this, feel free to reopen this.

Best!
Israel Soto.
