### ISSUE TITLE
A/B testing using Firebase RemoteConfig on Xamarin iOS

### ISSUE THREAD

**Issue by dalexsoto** [xamarin/GoogleApisForiOSComponents#132]
_From @tharanagaraj on March 16, 2018 19:34_

### Steps to Reproduce

1. Set up an A/B test using Firebase RemoteConfig for the project as described [here](https://components.xamarin.com/gettingstarted/firebaseiosremoteconfig)
2. Create and start an experiment. The only criteria we used was the bundle id of the project and rolled it out to some users (10% in this case).
3. Wait for an appropriate amount of time. The video tutorial says results should start trickling in after about half a day, some people suggest to wait for 2 days. We've been waiting for over 2 days.

### Expected Behavior
We expect to see data and the number of users increasing since we're able to see the test live on devices. 

### Actual Behavior
We're seeing the number of users is still 0 and there's no data yet. 

### Versions of Firebase packages
Xamarin.Firebase.iOS.Firebase InstanceID - 2.0.8
Xamarin.Firebase.iOS.Core - 4.0.13
Xamarin.Firebase.iOS.RemoteConfig - 2.0.3.1

### Environment

```
=== Visual Studio Community 2017 for Mac ===

Version 7.3.2 (build 12)
Installation UUID: 47b9fcdb-ba41-4e26-abd6-eb4db17c569f
Runtime:
	Mono 5.4.0.201 (2017-06/71277e78f6e) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504000201

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.0
SDK: Not installed
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/4.8.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Xamarin.Android ===

Version: 8.1.0.25 (Visual Studio Community)
Android SDK: /Users/tharanagaraj/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 25.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Apple Developer Tools ===

Xcode 9.0 (13247)
Build 9A235

=== Xamarin.iOS ===

Version: 11.6.1.2 (Visual Studio Community)
Hash: 6857dfcc
Branch: xcode9.2
Build date: 2017-12-04 21:20:41-0500

=== Xamarin.Mac ===

Version: 3.4.0.21 (Visual Studio Community)

=== Xamarin Inspector ===

Version: 1.2.2
Hash: b71b035
Branch: d15-1
Build date: Fri, 21 Apr 2017 17:57:12 GMT

=== Build Information ===

Release ID: 703020012
Git revision: 7d0c9d7ad46b125cf4b7bbf9532c0531b6433ce6
Build date: 2017-12-12 14:03:18-05
Xamarin addins: 6dddaa49fbecb2695fcdcd6b712eb269e288518c
Build lane: monodevelop-lion-d15-5

=== Operating System ===

Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Thu Jun 15 17:36:27 PDT 2017
    root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64


```

_Copied from original issue: xamarin/xamarin-macios#3774_

**Comment by tharanagaraj** [comment]
We now see the message "We have not received any data for your experiment". Has anybody been able to get this working? Just to reiterate, we're able to see the test live on devices, and everything appeared to be working fine while testing as well.

**Comment by SotoiGhost** [comment]
Hi @tharanagaraj!

Right now, Firebase Remote Config for iOS is on version 2.0.3.1 (a.k.a Firebase 4.4.0) which doesn’t include the A/B Testing bits yet, that must be the reason why is not working properly. I have the Remote Config update (v2.1.0, a.k.a Firebase 4.8.0) that includes Firebase A/B Testing bits in my TODO list but, because is still in beta phase, I’m prioritizing other task that I have. Right now, I cannot give an ETA of when this will be released.

That said, we are open to external contributions if you are willing to give it a spin. I can offer guidance if you go that route.

Best!
Israel Soto.

**Comment by tharanagaraj** [comment]
Hi @SotoiGhost !

Thanks a bunch for your reply and detailed explanation. That makes sense. Google did say that the minimum version of Firebase would have to be 4.5.0 and I double checked and verified that the packages weren't using it.

Sure, I'd love to take a stab at this and see how it goes. How do we get started?

Thanks,
Thara

**Comment by SotoiGhost** [comment]
Thanks a lot for wanting to contribute! I'll try to write a little contribution guide and try to be as clear as possible.

First of all, Firebase components in this repo are updated to main version 4.8.0, so, the Remote Config version that we must point is 2.1.0 (a.k.a 4.8.0). This is because Firebase APIs are kind of intertwined with them and making updates pointing different versions could make things not work properly.

One thing that would be nice to have and to make things easier for an update process is a file comparison app. I use [Kaleidoscope][1] but there are other free options out there. Here's the podspec that you must compare:

* [Remote Config v2.0.3][2] vs. [Remote Config v2.1.0][3]
* [A/B Testing v1.0.0][4]

That said, let's start with the update process:

1. First, create a fork of this repo.
2. On your fork, create a new branch from `master` (My name suggestion is `update/remoteconfig-2.1.0`).
3. Based on the podspec, these are the file that must be updated:
    * externals/Podifle
    * source/Firebase.RemoteConfig/FirebaseRemoteConfig.linkwith.cs
    * source/Firebase.RemoteConfig/Firebase.RemoteConfig.targets
    * nuget/Xamarin.Firebase.iOS.RemoteConfig.nuspec
4. In your favorite terminal app, go to **Firebase.RemoteConfig** folder and run `sh ../build.sh -t externals`.
5. In **externals/Pods** folder will be all the Firebase frameworks. Use [sharpie][5] to create the ApiDefinition.cs for both Firebase components from frameworks. I usually use these both commands:
    
    ```
    sharpie xcode -sdks
    sharpie bind -sdk iphoneosVersionNumber -n Firebase.Foo -f /path/to/Foo.framework/ -c -F/path/to/folder/framework/
    ```

    ```
    sharpie xcode -sdks
    sharpie bind -sdk iphoneos11.2 -n Firebase.Foo -scope /path/to/Foo.framework/Headers/ /path/to/Foo.framework/Headers/Foo.h -c -F/path/to/folder/framework/`
    ```

6. Get Remote Config v2.0.3 Framework and compare the headers with the Remote Config version located at **externals/Pods** folder with your favorite file comparison app.
7. Open the **samples/RemoteConfigSample/RemoteConfigSample.sln** and start updating the **ApiDefinition.cs** file. Add the Firebase A/B Testing binding inside of ApiDefinition.cs file in another namespace, my suggestion for the namespace is Firebase.ABTesting.
8. Run the sample on simulator and device with **Debug** and **Release* configuration to make sure that everything is working properly.
9. Update version number in **Readme.md** and

That's it! I hope this is sufficiently clear to make the update.

If you have any doubt, don't hesitate to ask.

Thanks in advance for contributing!

Best,
Israel Soto.

[1]: https://www.kaleidoscopeapp.com/
[2]: https://github.com/CocoaPods/Specs/blob/master/Specs/f/2/a/FirebaseRemoteConfig/2.0.3/FirebaseRemoteConfig.podspec.json
[3]: https://github.com/CocoaPods/Specs/blob/master/Specs/f/2/a/FirebaseRemoteConfig/2.1.0/FirebaseRemoteConfig.podspec.json
[4]: https://github.com/CocoaPods/Specs/blob/master/Specs/d/c/1/FirebaseABTesting/1.0.0/FirebaseABTesting.podspec.json
[5]: https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/binding/objective-sharpie/

**Comment by tharanagaraj** [comment]
Hey @SotoiGhost 

Thank you for the comprehensive guide. I've just started looking into it. It seems fairly straightforward except for one thing.

We will need to create a new package/binding for the A/B Testing v1.0.0 pod, right? 
Can we model the cake script after the other scripts like [this](https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/Firebase.RemoteConfig/build.cake) one? 

Also, in point 5 above, when you say " Use sharpie to create the ApiDefinition.cs for both Firebase components from frameworks", you mean the updated RemoteConfig and the new A/B testing component, right? Or have I missed something?

Just wanted to clarify this before making any changes. Please let me know if my understanding is not correct.

Best,
Thara

**Comment by SotoiGhost** [comment]
@tharanagaraj yw! I'll answer between lines.

> We will need to create a new package/binding for the A/B Testing v1.0.0 pod, right?
> Can we model the cake script after the other scripts like this one?

Yesterday, I would have told you no, to add A/B Testing inside of Remote Config because Google has A/B Testing documentation inside of Remote Config, but on second thought, I say yes, add A/B Testing as a separate component with its own folder to keep versions separated. You can base yourself on the file that you showed me. The dependency on **cake.build** would be **Firebase.RemoteConfig**.

Anyway, if you feel that A/B Testing must be inside of Remote Config, go ahead with that way, I have no problems, I'll leave the decision to you. If Google decides to make A/B Testing bigger enough to have its own documentation section, we can split the component later.
 
> Also, in point 5 above, when you say " Use sharpie to create the ApiDefinition.cs for both Firebase components from frameworks", you mean the updated RemoteConfig and the new A/B testing component, right? Or have I missed something?

Yep, the updated RemoteConfig and the new A/B testing component.

A tip that I can give you is, after that you have generated the **ApiDefinition.cs**, try to order the generated C# classes and delegates as you have it in Objective-C headers, this helps a lot the update process later. Also, when I update a component, what I usually do is to generate the updated **ApiDefinition.cs**, compare the Objective-C headers with the old version and I only add the new stuff to ApiDefinition.cs.

Hope this help.

Any doubt, don't hesitate to ask.

Best,
Israel Soto.

**Comment by SotoiGhost** [comment]
Hi @tharanagaraj! Just wondering, how are you doing with the A/B Testing binding? Do you need some help with something?

**Comment by tharanagaraj** [comment]
Hi Israel!

I started it and made some progress. But some other priorities took over. Now I’m out of town for a bit. Should be able to continue with it when I’m back, which is probably in a day or two. Apologies for the delay!

**Comment by tharanagaraj** [comment]
Hi @SotoiGhost ,

I think I was able to update everything related to RemoteConfig. But I do have a question about the ABTesting setup. I wrote a cake script for it, modeled on the script we talked about, but ran into the following error:

> 

Error: The assembly 'Cake.XCode, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' 
is referencing an older version of Cake.Core (0.12.0). 
This assembly need to reference at least Cake.Core version 0.26.0. 
Another option is to downgrade Cake to an earlier version. 
It's not recommended, but you can explicitly opt-out of assembly verification 
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true", 
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true", 
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)

> 

So, I read up about configuration pinning. My question is, should this be changed at the global level or only for this specific component?

**Comment by tharanagaraj** [comment]
Hi @SotoiGhost 
Attached. Please let me know what could potentially be wrong. 
[CakeScript.txt](https://github.com/xamarin/GoogleApisForiOSComponents/files/1917913/CakeScript.txt)

**Comment by SotoiGhost** [comment]
@tharanagaraj what is the command that you are running?

**Comment by tharanagaraj** [comment]
@SotoiGhost I used `./build.sh` as outlined [here](https://github.com/cake-build/cake#example).
Could you please tell me what I am missing?

**Comment by SotoiGhost** [comment]
Hi @tharanagaraj! What's the actual status of Remote Config? Right now, I'm working on Firebase 5.0 update and I'm about to touch Remote Config. I'm wondering if you want me to update it or if you have an update ready so I can look at it.

Best!
Israel Soto.

**Comment by tharanagaraj** [comment]
Hey @SotoiGhost ! Apologies about not following up. 
Priorities changed on our end, so this took a back seat. But if you give me another day, I can create a PR with whatever changes I have so far with RemoteConfig. But if you feel like you want to go ahead and update it, that's fine too. Please let me know. 

Thank you!

**Comment by SotoiGhost** [comment]
@tharanagaraj Go ahead and create the PR with the changes you have, I will be glad to continue the update with your changes.

**Comment by tharanagaraj** [comment]
Hi @SotoiGhost - just wondering if the A/B testing bits are going to be part of your update?

**Comment by SotoiGhost** [comment]
Hey @tharanagaraj! Yep, it is part of the update, I already finished the update. I'm waiting for the approval of the update.

**Comment by tharanagaraj** [comment]
That's awesome news! Looking forward to trying it out. Thank you very much, @SotoiGhost !

**Comment by SotoiGhost** [comment]
@tharanagaraj A/B Testing is live now. Closing this issue.

Best!
