### ISSUE TITLE
Can't add Xamarin.Google.iOS.SignIn to a project, get error Could not resolve reference "C:\Users\james\AppData\Local\XamarinBuildDownloadCache\GSgnI-4.2.0\Frameworks\GoogleSignIn.framework"

### ISSUE THREAD

**Issue by banshee** [xamarin/GoogleApisForiOSComponents#224]
Add the Xamarin.Google.iOS.SignIn nuget to a brand-new iOS project created with the iOS App (Xamarin) template in Visual Studio.

You'll get this error:

Severity	Code	Description	Project	File	Line	Suppression State
Warning		Could not resolve reference "C:\Users\james\AppData\Local\XamarinBuildDownloadCache\GSgnI-4.2.0\Frameworks\GoogleSignIn.framework". If this reference is required by your code, you may get compilation errors.	App2

**Comment by banshee** [comment]
I'm using Xamarin.Google.iOS.SignIn 4.2.0

**Comment by banshee** [comment]
On Windows.  On mac, it blows up in a totally different way (see issue 226)

**Comment by SotoiGhost** [comment]
@banshee This error commonly happens when Xamarin.Buil.Download NuGet is not restored correctly. Please, remove the NuGet and add it again, please.

Also, this could be related to #226. If adding it again doesn't work, please, try following the [comment][1] on #226 to see if that resolves the problem.

[1]: https://github.com/xamarin/GoogleApisForiOSComponents/issues/226#issuecomment-454592799

**Comment by Cliffy786** [comment]
@banshee I can't run that command in my nuget package manager console, I can run rm ~/.nuget, when I add the -rf option though, the console just throws me an error because it doesn't recognized the the -rf option.

**Comment by banshee** [comment]
> when I add the -rf option though, the console just throws me an error because it doesn't recognized the the -rf option.

It's just a command to recursively remove the entire directory.
