### ISSUE TITLE
Question: Firebase Crashlytics setup

### ISSUE THREAD

**Issue by b12kab** [xamarin/GoogleApisForiOSComponents#236]
In the [Crashlytics instructions](https://github.com/xamarin/GoogleApisForiOSComponents/blob/03c7782cbc16d874e57ba01db31a6be8e6b8aa12/Firebase.Crashlytics/component/GettingStarted.md) page in the "Set up manual initialization" section, it shows this:

> // Add Crashlytics
> Fabric.Fabric.With (typeof (Crashlytics));

When I run this it gives me this error: 
Objective-C exception thrown.  Name: FABException Reason: [Fabric] Value of Info.plist key "Fabric" must be a NSDictionary.

Due to the GDPR and California reporting requirements, I'm giving the user to opt out of the automatic crash uploading. This error reminds me of the original Fabric (i.e. non-Firebase) Crashlytics.

I've imported the Google plist and set the build action to BundleResource. The Crashlytics instructions don't mention any other setup that is needed.

In case it helps, this is the try block in the method:

```csharp                
try
{
    Crashlytics.Configure();
    Fabric.Fabric.SharedSdk.Debug = true;

    Fabric.Fabric.With(typeof(Crashlytics));
}
catch (Exception exception)
{
    System.Diagnostics.Debug.WriteLine("Init -  failed - " + exception.Message);
    return true;  // it's an error
}
```

**Comment by b12kab** [comment]
I should also mention this is a Dependency Injection and called from a View Model.

**Comment by SotoiGhost** [comment]
@b12kab This happens because the Crashlytics component cannot find any api key. Crashlytics looks for an api key inside of the `Info.plist` or `GoogleService-Info.plist`.

The old way to get the api key is by logging into [Fabric][1] page and generating the api key, but this way is now deprecated due to Fabric will move into Firebase soon.

The new way is by adding the `GoogleService-Info.plist` into your project and by initializing `Firebase` in your app before Crashlytics configuration:

```csharp
Firebase.Core.App.Configure ();
```

This will make that Crashlytics can find the api key.

You will need to add the `Xamarin.Firebase.iOS.Core` Nuget package to achieve this.

This step is missing from docs, a graet apology for this.

Hope this helps you.

Best!
Israel Soto.

[1]: https://fabric.io/login?utm_campaign=discover&utm_medium=natural
