### ISSUE TITLE
Google MobileAds IOS 7.38 no Ad Adapter

### ISSUE THREAD

**Issue by zeerakMush** [xamarin/GoogleApisForiOSComponents#244]
Hello,

I just updated to version 7.38 of mobile.Ads.Ios. it is now not displaying me test reward video ads previously it was working for simulators  and now it is giving me following error . 
"{Request Error: Cannot find an ad network adapter for mediation.}"

I am using following test id
"ca-app-pub-3940256099942544/1712485313"

**Comment by DigitalNut** [comment]
I also updated to V7.38 of Xamarin.Google.iOS.MobileAds and my (banner) ads stopped showing up. Just shows blank. Was working with the previous version (V7.32 I believe). This is the error message I'm getting in Debug:
"<Google> Cannot find an ad network adapter with the name(s): com.google.DummyAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target."

**Comment by SotoiGhost** [comment]
@zeerakMush, @DigitalNut Are you using Google's id tests?

**Comment by DigitalNut** [comment]
@SotoiGhost I get the error with both Test ID and real ID.

**Comment by DigitalNut** [comment]
FYI: I went back to V7.32 and Ads are working (showing up in my app on real device - iPad).

**Comment by SotoiGhost** [comment]
@DigitalNut @zeerakMush I tested our samples using Google's and real ids, and it's working for me. I did a little investigation of this and some users suggest that this issue happens due to a "user account problem". Can you follow [this thread][1] from the beginning and try the solutions provided? Thanks in advance.

[1]: https://groups.google.com/forum/#!category-topic/google-admob-ads-sdk/23vdojgNw2U

**Comment by SotoiGhost** [comment]
Closing this issue now since no response was received from the owner of the issue.

If anyone faces something related to this, please, open a new issue. Thanks in advance!

Best!
Israel Soto.
