### ISSUE TITLE
Xamarin.Google.iOS.Maps 3.0.3 build error for simulator when deployment target = 8.0

### ISSUE THREAD

**Issue by philmoz** [xamarin/GoogleApisForiOSComponents#255]
Steps to reproduce:
- Create blank Xamarin.Forms app using .Net Standard for shared code.
- Add Xamarin.Google.iOS.Maps 3.0.3 NuGet package to iOS project and Shared code project.
- Set Deployment Target to 8.0 in iOS Info.plist
- Build for iOS simulator (any hardware device and iOS version)

Build results in the following error:
MT5209: Error: targeted OS version does not support use of thread local variables in __ZN9GMSx_absl18container_internal21ShouldInsertBackwardsEmPa for architecture x86_64

Building for physical devices works.
Setting Deployment Target to 9.0 or higher works; but is not an acceptable workaround.

**Comment by SotoiGhost** [comment]
Since v3.0.0 of Google Maps and Places, Google decided to drop iOS 8. Now the minimum target version is iOS 9. This is out of our control. You can see this in the [Google Maps podspec][1].

Sorry for the inconveniences that this may cause.

Best!
Israel Soto.

[1]: https://github.com/CocoaPods/Specs/blob/master/Specs/a/d/d/GoogleMaps/3.0.3/GoogleMaps.podspec.json#L14

**Comment by spatialguy** [comment]
> Since v3.0.0 of Google Maps and Places, Google decided to drop iOS 8. Now the minimum target version is iOS 9. This is out of our control. You can see this in the [Google Maps podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/a/d/d/GoogleMaps/3.0.3/GoogleMaps.podspec.json#L14).
> 
> Sorry for the inconveniences that this may cause.
> 
> Best!
> Israel Soto.

Thank you @SotoiGhost !
