### ISSUE TITLE
MLKitSample build fails

### ISSUE THREAD

**Issue by DeanFaizal** [xamarin/GoogleApisForiOSComponents#257]
![Screen Shot 2019-03-29 at 10 01 29 AM](https://user-images.githubusercontent.com/2334530/55241708-08151880-5212-11e9-8e08-8dfe1ee954dd.png)

It says framework not found for FirebaseCore. 

I followed the instructions, have cocoapods installed, ran build.sh for each target except clean. I looked in the Firebase.Core/externals directory and the .frameworks were missing so I created a new ios project & ran pod install to generate the frameworks. Tried to reference the new .frameworks but received the same error message. What am I doing wrong?

**Comment by SotoiGhost** [comment]
@DeanFaizal Can you try again following these steps?

1. Checkout to `Firebase/MLKit/0.13.0.1` tag using `git checkout tags/Firebase/MLKit/0.13.0.1 -b <a_branch_name>`
2. Navigate to `Firebase.MLKit` folder and run `sh ../build.sh -t=clean`
3. Run `sh ../build.sh -t=samples`
4. Open MLKit sample and try to build.

Let me know your results. Thanks in advance!

**Comment by DeanFaizal** [comment]
Thanks @SotoiGhost. It works! Previously I had followed the steps to build core from the readme:

> cd Firebase.Core
> sh ../build.sh --target=libs

but not Firebase.MLKit

**Comment by SotoiGhost** [comment]
@DeanFaizal Glad that the build worked! Targeting `libs` should work, but I noticed that since Xcode 10, sometimes, Xcode doesn't build some frameworks properly. It builds the framework structure but, for some reason, it deletes the `Foo.a` lib when creating the fat library. That's the reason for the error you faced. 

If you face a similar error again, just do a `sh ../build.sh -t=clean` first and then `sh ../build.sh -t=libs` or the desired target.

Closing this issue now. If you have any other question, please, open a new issue.

Happy coding!
Israel Soto.
