### ISSUE TITLE
iOS Crashlytics Crash Report on Every try/catch

### ISSUE THREAD

**Issue by udevnull** [xamarin/GoogleApisForiOSComponents#276]
Running
- `Xamarin.Firebase.iOS.Core: 5.2.0`
- `Xamarin.Firebase.iOS.Crashlytics: 3.10.9`

Initialised Crashlytics in `AppDelegate.cs`

```
Fabric.Fabric.With(typeof(Crashlytics));
Firebase.Core.App.Configure();
Crashlytics.Configure();
```

The app sends a report to crashlytics on every `try/catch` statement which is obviously not what I'm trying to achieve. How do I stop this?

**Comment by udevnull** [comment]
Any update on this?

**Comment by MatFillion** [comment]
We're also observing this and it's raising a ton of false data in the firebase dashboards.

I'd like to add more informations and hopefully it can help the investigation.

It seems caught exceptions from a Xamarin.iOS app are being reported as crashes in Firebase.Crashlytics. In fact, the application doesn't crash and the exception is handled by application code.

### Here is the code reproducing the issue.
```
try
{
    // The following line obviously throws an exception (null ref).
    var a = (DateTimeOffset)(object)null;
}
catch (Exception e)
{
    // Handle the error.
}
```

### Current behavior:
This code throws an exception and handles it in a catch block. The application doesn't crash. However, this creates a crash report in the Firebase console.

### Expected behavior:
Crash reports are not created unless an actual crash occurs.

### Additional info:
If exception is thrown like this crashlytics will not report it (as expected):
```
try
{
    throw new Exception("boom");`
}
catch (Exception e)
{
    // Handle the error.
}
```
So it seems the problem only occurs when exception is thrown in native code.


We are using https://www.nuget.org/packages/Xamarin.Firebase.iOS.Crashlytics/ 
version=3.10.9

If you need a complete repro project in X.Forms or Uno we can provide this.


@udevnull if the information I just added does not match what you're experiencing let me know and I'll move this comment to a new issue instead.

**Comment by udevnull** [comment]
Any update on this?

**Comment by SotoiGhost** [comment]
A new version of Firebase Crashlytics has been released. Can you try updating to the most recent version and see if the error is still happening? Thanks in advance!

**Comment by SotoiGhost** [comment]
We have not received the requested information. If you are still experiencing this issue, please, open a new issue related to this. Thanks!

**Comment by albertoaloisi-acc** [comment]
Hi we are having the same issue described with the latest version of Xamarin.Firebase.iOS.Crashlytics = 3.14.0, do you have any update or hint ?
Thanks

**Comment by sunilsolankilnt** [comment]
We are also facing same issue in Xamarin.Firebase.iOS.Crashlytics = 3.14.0.  Please suggest any fix
