### ISSUE TITLE
iOS Xamarin app is getting many crashes related the Google Ads SDK

### ISSUE THREAD

**Issue by congpt-xamarindev** [xamarin/GoogleApisForiOSComponents#355]
Here is the discussion about this issue https://groups.google.com/forum/#!category-topic/google-admob-ads-sdk/ios/I4EEWrPPbSc
I have integrated Google Ads SDK version 7.38(not the latest one) to my Xamarin iOS app. My app is facing exact same issue as what the topic above is talking about. I've also tried to solve it by adding a gad_preferred_webview key with value of wkwebview in app's Info.plist file. But my app got performance issue in loading the ads. 
I've checked the release notes of the latest SDK(7.53.0). Google might have fixed some bugs related my issue. However, when I check the Xamarin Google Ads SDK version from Nuget. It is 7.47. I think it was out update for a while. 
Could you please help me to have the update for this SDK? OR any solution to fix my issue. Thank you so much.

**Comment by TuanNA-MTITech** [comment]
My xamarin.ios app also got crash continuously after I build with iOS13 SDK (XCode 11)
This problem was known as Google Ads Mobile iOS SDK issue. 
Do Xamarin Dev have any plan for binding Mobile Ads to latest one (v7.53.1) that hope fixing this issue?

![Screen Shot 2020-01-15 at 09 01 24](https://user-images.githubusercontent.com/38967069/72398527-cee46f80-3775-11ea-8360-1b6da165fd9d.png)
Crashlytic logs:

`Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x1c141aa48 __exceptionPreprocess
1  libobjc.A.dylib                0x1c1141fa4 objc_exception_throw
2  Foundation                     0x1c18f0f08 -[NSISEngine tryToOptimizeReturningMutuallyExclusiveConstraints]
3  Foundation                     0x1c16f203c -[NSISEngine withBehaviors:performModifications:]
4  UIKitCore                      0x1c5853510 __57-[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]_block_invoke
5  UIKitCore                      0x1c58532c4 -[UIView(AdditionalLayoutSupport) _switchToLayoutEngine:]
6  UIKitCore                      0x1c5852420 -[UIView(AdditionalLayoutSupport) _initializeHostedLayoutEngine]
7  UIKitCore                      0x1c584696c -[UIView(UIConstraintBasedLayout) _layoutEngine_windowDidChange]
8  UIKitCore                      0x1c5919dec -[UIView(Internal) _didMoveFromWindow:toWindow:]
9  UIKitCore                      0x1c5919f88 -[UIView(Internal) _didMoveFromWindow:toWindow:]
10 UIKitCore                      0x1c5919f88 -[UIView(Internal) _didMoveFromWindow:toWindow:]
11 UIKitCore                      0x1c590e334 __45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke
12 UIKitCore                      0x1c590e21c -[UIView(Hierarchy) _postMovedFromSuperview:]
13 UIKitCore                      0x1c591cb24 -[UIView(Internal) _addSubview:positioned:relativeTo:]
14 UIKitCore                      0x1c5641df4 -[UITableView _addSubview:positioned:relativeTo:]
15 UIKitCore                      0x1c58b6810 -[UIScrollView _addContentSubview:atBack:]
16 UIKitCore                      0x1c5641b2c -[UITableView _addContentSubview:atBack:]
17 UIKitCore                      0x1c5662124 __53-[UITableView _configureCellForDisplay:forIndexPath:]_block_invoke
18 UIKitCore                      0x1c5915e68 +[UIView(Animation) performWithoutAnimation:]
19 UIKitCore                      0x1c5661938 -[UITableView _configureCellForDisplay:forIndexPath:]
20 UIKitCore                      0x1c5672ca0 -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:]
21 UIKitCore                      0x1c56402c4 -[UITableView _updateVisibleCellsNow:]
22 UIKitCore                      0x1c565d48c -[UITableView layoutSubviews]
23 UIKitCore                      0x1c59233d0 -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
24 QuartzCore                     0x1c7e867dc -[CALayer layoutSublayers]
25 QuartzCore                     0x1c7e8c958 CA::Layer::layout_if_needed(CA::Transaction*)
26 QuartzCore                     0x1c7e97578 CA::Layer::layout_and_display_if_needed(CA::Transaction*)
27 QuartzCore                     0x1c7ddff1c CA::Context::commit_transaction(CA::Transaction*, double)
28 QuartzCore                     0x1c7e09c08 CA::Transaction::commit()
29 QuartzCore                     0x1c7e0a5fc CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*)
30 CoreFoundation                 0x1c1397e68 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
31 CoreFoundation                 0x1c1392d54 __CFRunLoopDoObservers
32 CoreFoundation                 0x1c1392afc CFRunLoopRunSpecific
33 WebCore                        0x1c935b17c RunWebThread(void*)
34 libsystem_pthread.dylib        0x1c1135d8c _pthread_start
35 libsystem_pthread.dylib        0x1c113976c thread_start`

**Comment by SotoiGhost** [comment]
Hi guys! Just letting you know that Google Mobile Ads v7.53.1 has been released! Hope this fixes your issues. If something happens, please, let us know. Best!

**Comment by TuanNA-MTITech** [comment]
The root cause of Crash issue related to UIWebView that very old in Mobile Ads.
In Release Note, The new version v7.55.0 that total remove UIWebView and replaced by WKWebView.
https://developers.google.com/admob/ios/rel-notes

I think the correct version that fixed this issue is v7.55.0.
Do you have plan to bind Mobile Ads SDK to v7.55.0?

**Comment by SotoiGhost** [comment]
> Do you have plan to bind Mobile Ads SDK to v7.55.0?

@TuanNA-MTITech not for now, I don't have an ETA of when this component will be updated.

That said, community PR are very welcome! We would really appreciate your help! Best!

**Comment by SotoiGhost** [comment]
I have just talked with my manager about this and this has been prioritized. We are gonna work on this very soon.

@TuanNA-MTITech or @congpt-xamarindev can you file a new issue about this? Thanks in advance!

**Comment by TuanNA-MTITech** [comment]
wow, thank you very much for your effort. We are looking forward to getting your results 👍
