### ISSUE TITLE
Device crashes with error: FirebaseFirestore.framework/FirebaseFirestore tried but couldn't find Protobuf.framework

### ISSUE THREAD

**Issue by vincooys** [xamarin/GoogleApisForiOSComponents#376]
I'm having this issue and not able to pinpoint where it's coming from. Getting the error from the device log:

@rpath/Protobuf.framework/Protobuf not found for /private/var/containers/Bundle/Application/3343439-jflkd-34343--/APPNAME/Frameworks/FirebaseFirestore.framework/FirebaseFirestore, tried but didn't find: '/private/var/containers/Bundle/Application/434343-2ADD-3433-543333D22/APPNAME/Frameworks/Protobuf.framework/Protobuf'

I have the following packages installed in my Xamarin.iOS project:

Xamarin.Firebase.iOS.Analytics (6.2.1)
Xamarin.Firebase.iOS.Auth (6.4.2)
Xamarin.Firebase.iOS.CloudFirestore (1.4.2.2)
Xamarin.Firebase.iOS.CloudMessaging (4.1.1.2)
Xamarin.Firebase.iOS.Core (6.6.0)
Xamarin.Firebase.iOS.Crashlytics (3.14.0.3)
Xamarin.Firebase.iOS.InstanceID (4.3.0)
Xamarin.Firebase.iOS.Storage (3.4.0.1)
Xamarin.Build.Download (0.9.0)

I've tried to delete every folder I can think of (XamarinBuildCache, obj, bin, etc). Rolling back versions of packages to previous versions--but nothing I do will stop my device from crashing on startup and displaying this error in the device log :(

It all started when I installed the CloudMessaging package. Everything else works fine--I've spent 3 days on this one, with no luck!!

**Comment by SotoiGhost** [comment]
@vincooys Please, downgrade Firebase NuGets to previous version. Right now, Firestore doesn't work with most recent versions of Firebase. We are working on an update that fixes this. Sorry for the inconveniences that this can cause!

**Comment by vinco83** [comment]
@SotoiGhost  Thanks for the response--I'll try downgrading all of the packages tonight and report back if I run into anymore issues!

Should I just roll each package back one version? Or are there specific version numbers/releases they should be set to?

**Comment by SotoiGhost** [comment]
I think just rolling back one version should work. Should set packages before Feb 24th release

**Comment by vinco83** [comment]
@SotoiGhost Rolling every package back one version worked! Hallelujah! 3 days spent trying to figure this out lol I swear I tried rolling the versions back days ago and it didn't work...but who knows what sort of caching issues I was experiencing then.

Anyways, thanks so much for the recommendation/solution!

**Comment by haiduong741** [comment]
> @SotoiGhost Rolling every package back one version worked! Hallelujah! 3 days spent trying to figure this out lol I swear I tried rolling the versions back days ago and it didn't work...but who knows what sort of caching issues I was experiencing then.
> 
> Anyways, thanks so much for the recommendation/solution!

You should use Xamarin.Build.Download 4.11 version.

**Comment by robinryf** [comment]
Hi, thank you for taking the time on fixing this. Any news on the updated packages?

I wanted to highlight a problem due April 2020 for this change. Since we can't upgrade Firebase because of this issue we will get rejected by Apple submission in April because Firebase still uses UIWebView in the older/previous version. 
https://developer.apple.com/news/?id=12232019b

In my case it seems that Xamarin.Firebase.iOS.Auth or one of its dependencies is still using UIWebView. When I deploy to Apple with Xamarin.Firebase.iOS.Auth 6.2.1.1 I get:
`"ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020"`

When I deploy with Xamarin.Firebase.iOS.Auth 6.4.2 the processing from Apple runs through smoothly.

In my case I "only" use Xamarin.Firebase.iOS.CloudFirestore and Xamarin.Firebase.iOS.Auth. And when I update Xamarin.Firebase.Auth I get the error with Protobuf described in the posts above.

Cheers

**Comment by vhugogarcia** [comment]
I am facing the same issues. I am using the latest versions from April and I still get the error:
`dyld: dependent dylib '@rpath/Protobuf.framework/Protobuf' not found for Frameworks/FirebaseFirestore.framework/FirebaseFirestore'`

Any workaround?

**Comment by bluejeff31** [comment]
I just updated to the latest release and am still getting this same error for `FirebaseMessaging.framework`

**Comment by SotoiGhost** [comment]
Hi guys! Please, remove your **bin** and **obj** folders, delete the XBD cache located at:

* **_Mac:_**`~\Library\Caches\XamarinBuildDownload`
* **_Windows:_** `C:\Users\[username]\AppData\XamarinBuildDownloadCache\`

As now Firebase Cloud Firestore does not depend on `Protobuf.framework`anymore.

**Comment by Redth** [comment]
We are closing this issue since no response was received.  Please open a new issue referring to this one if you have more information.
