### ISSUE TITLE
About GADInvalidInitializationException Reason: The Google Mobile Ads SDK was initialized without an application ID

### ISSUE THREAD

**Issue by kaanakyalcin** [xamarin/GoogleApisForiOSComponents#383]
I was using Xamarin.Google.iOS.Mobileads 7.38.0 and I update the package to version 7.53.1.
After that It starts to getting error. Error is like below:

> Objective-C exception thrown GADInvalidInitializationException Reason: The Google Mobile Ads SDK was initialized without an application ID

I figure out when I update the google.ios.mobileads SDK from NuGet, NuGet doesn't install new dependencies in which they are Xamarin.Build.Download and Xamarin.Firebase.ios.core. I ınstalled them manually but still not working

**Comment by SotoiGhost** [comment]
Hi @kaanakyalcin! Thank you for reporting this and an apology for the inconveniences that this can cause.

Can you, please, try adding the application ID to your [Info.plist][1] and calling [`MobileAds.SharedInstance.Start`][2] instead of using the old way? Thanks in advance!

[1]: https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/samples/Firebase/AdMob/AdMobSample/Info.plist#L37-L38
[2]: https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/samples/Firebase/AdMob/AdMobSample/AppDelegate.cs#L44

**Comment by kaanakyalcin** [comment]
Adding GADIsAdManagerApp property to info.plist fixed the problem

**Comment by SotoiGhost** [comment]
@kaanakyalcin Good to know that! I'm closing this issue now.
