### ISSUE TITLE
Outdated bindings to Google ML Kit Vision Text Regognition api

### ISSUE THREAD

**Issue by deelw** [xamarin/GoogleApisForiOSComponents#472]
Because we’re using ML Kit for Firebase (https://firebase.google.com/docs/ml-kit) for on-device text recognition and this is an old version, we need to migrate to the actual version of ML Kit (https://developers.google.com/ml-kit/vision/text-recognition ).

As Dutch government, we develop our apps using Xamarin and we need to migrate as well our Xamarin.iOS as our Xamarin.Android implementation.

For Xamarin.iOS we’re using nuget package Xamarin.Firebase.iOS.MLKit.Vision version 0.21.0 from Microsoft while for Xamarin.Android we’re using nuget package Xamarin.GooglePlayServices.Vision version 120.1.3, also from Microsoft. These packages contain C# bindings to ML Kit for Firebase.

Surprisingly there seems to be no Xamarin nuget packages available for the current GoogleMLKit/TextRecognition (https://developers.google.com/ml-kit/vision/text-recognition). Neither for Xamarin.iOS nor for Xamarin.Android.

We did try to make bindings ourselves. While we did succeed in making and invoking these bindings, text is never recognized. In the console output the MLKit framework did write the following messages:

- [lvl=3] +[MLKITx_CCTClearcutUploader crashIfNecessary] Multiple instances of CCTClearcutUploader were instantiated. Multiple uploaders function correctly but have an adverse affect on battery performance due to lock contention.
- Failed to locate required resources. Please verify the resource bundle is imported.
- [lvl=3] -[MLKITx_GIPPseudonymousIDStore initializeStorage] Shared App Groups unavailable

We ask you to make nuget packages available for the current versions of Google MLKit, specifically for cocoapod GoogleMLKit/TextRecognition and maven repository com.google.android.gms:play-services-mlkit-text-recognition.

Related issue: https://github.com/xamarin/GooglePlayServicesComponents/issues/420

**Comment by deelw** [comment]
@SotoiGhost you've helped me a year a go with bindings for iOS. I heard the Components team was dissolved. Could you please help us by either making new Google ML Kit Vision TextRecognition (no Firebase) api's available or support us in making our own bindings work?

As you can read in the issue text, we successfully generated bindings. With our bindings we can invoke the MLKTextRecognizers ProcessImage and ResultsInImage methods. That the framework is successfully invoked is confirmed by the fact that the MLKTextRecognitionCallback of the ProcessImage method is called, but text is never recognized while the error object is null and an instance of the MLKText object is returned. We've tried all orientation flags. In the application console there are three messages (mentioned in the initial issue text above).

Could you or an experienced colleague of yours help us please? Thank you very much in advance!

Here some details for your information:
- I made a podfile (see under) because sharpie pod init 'GoogleMLKit/TextRecognition' resulted in a pod file using pod 'GoogleMLKit'
- I used pod update instead of sharpie because sharpie has no option to use the existing podfile
- after installing cocoapods I needed to call pod repo update to be able to successfully call the pod update command
- Before calling sharpie pod bind I had to unselect Mac for each project target (General tab -> deployment info) in the XCode Pods project (./Pods/Pods.xcodeproj)
- In my Xamarin Bindings library I only included MLKitTextRecognition_ApiDefinitions.cs and MLKitVision_ApiDefinitions.cs and I added a native reference to all the framework files (from the ./Bindings folder).
- In my iOS project I had to set the linker behavior to don't link

**Podfile**
```
platform   :ios, '14.3'
--
install! 'cocoapods',   :integrate_targets => false
target   'ObjectiveSharpieIntegration' do
use_frameworks!
 
pod   'GoogleMLKit/TextRecognition'
end
```

**Comment by deelw** [comment]
@mattleibow could you please help me with this issue? It's enough for me when I have local working bindings (only text recognition), while it would be very nice when the bindings would be globally available as a nuget package.

**Comment by deelw** [comment]
Here a solved issue i found with the same error, maybe this helps solving the cause?
https://github.com/xamarin/GoogleApisForiOSComponents/issues/382

**Comment by mavispuford** [comment]
@deelw Were you ever able to get your bindings to work?  I'm just starting down that path.  Thanks for detailing some of your process in the above comment, by the way.

**Comment by deelw** [comment]
@mavispuford yes, my bindings did work but without succesfull text recognition (the ocr result callback function was called, so the interaction was succesfull). However, reproducing the steps now results in a xamarin iOS project with linker errors.

**Comment by mavispuford** [comment]
@deelw I was able to get iOS bindings working with successful text recognition.  My guess is that you were missing the necessary resources in your bindings project that are needed for ML Kit (machine learning models etc.).  If you take a look in the MLKitTextRecognition pod folder, you'll see them:

![image](https://user-images.githubusercontent.com/2214272/117862793-4b933b00-b250-11eb-896a-29308bb96376.png)

[This targets file](https://github.com/xamarin/GoogleApisForiOSComponents/blob/main/source/Firebase/MLKit.Vision/MLKit.Vision.targets) for the old Firebase ML Kit Vision bindings was a great reference for me, because I later had linking errors in Release mode.  Making sure the Frameworks were set up correctly in the bindings project resolved them.

[Here's what my csproj file looks like.](https://gist.github.com/mavispuford/f3173af47f93df91348c53908b08a29a).  The two ApiDefinitions.cs files were generated using the following Sharpie commands:

`sharpie bind -o MLKitVisionBindings -sdk iphoneos14.4 -n MLKitVision -framework ./MLKitVision`

`sharpie bind -o MLKitTextRecognitionBindings -sdk iphoneos14.4 -n MLKitTextRecognition -framework ./MLKitTextRecognition`

**Comment by deelw** [comment]
@mavispuford Thank you very much! I'll try it as soon as possible. I'll let you know

**Comment by deelw** [comment]
@mavispuford
I think you did use the MLKitCommon, MLKitTextRecognition and MLKitVision frameworks straight from a **pod update** resulting in the contents of the Dependency/Pods directory?

For the Dependency/PodBuilder/Prebuilt contents I tried to use PodBuilder like you did. I did make a XCode iOS app project and workspace only because the PodBuilder requires them. Copied my podfile into the project directory. I was able to run pod_builder init. But **pod_builder build_all** did fail. Can you tell me how you did that?

Thanks for your help!

**Comment by mavispuford** [comment]
Here are the steps that I took for PodBuilder (**but note that I ended up dropping it and simplified my bindings project quite a bit** - I'll explain below):

- I created an empty XCode project with my podfile referencing the 'GoogleMLKit/TextRecognition' pod
- I ran `pod_builder init` to create the PodBuilder folder
- Ran `pod_builder build_all` to build all pods
- The resulting frameworks were located in `PodBuilder/Prebuilt`
- Pod-Builder skips any pods that already have frameworks.  Those pods are in their normal location in the `Pods` directory.

So I mentioned above that I stopped using PodBuilder to build my fat binaries.  The reason is that even though I had success building my bindings DLL and popping it in a simple Xamarin app, it caused problems with our other app because it was referencing Firebase for analytics/push notifications and the two had conflicts with their native dependencies. I looked around and noticed that the majority of the native dependencies are also in [Firebase.Core](https://github.com/xamarin/GoogleApisForiOSComponents/blob/main/source/Firebase/Core/Core.csproj).  So in my bindings project, I removed most of the native references and referenced the Firebase.Core NuGet package instead.  This works great for us and doesn't have any conflicts with our other packages references anymore.

[Here's what the bindings csproj file looks like now.
](https://gist.github.com/mavispuford/d59acc375061ff356a445153f4bd0d35)

**Comment by deelw** [comment]
@mavispuford 
Yes, it's working! Thanks you very much!

I have one question about your latest solution: How did you prevent the Firebase.Core nuget package from being stripped because it's not explicitly referenced from code?
I did so by including a static class with a private static Action reference = Firebase.Core.App.Configure; but maybe you did use a more elegant way?

**Comment by mavispuford** [comment]
@deelw That's great!  I'm glad to hear it.

For Android, we have an r8.cfg to prevent linking with entries like this:
```
-keep class com.google.firebase.** { *; }
-keep class androidx.camera.core.** { *; }
-keep class com.google.mlkit.vision.** { *; }
```

As for iOS, I don't think I did anything special to prevent it from being linked out.  We were actually already using Firebase.Core in our app, since we use Firebase for push notifications and analytics.  Since you're not using it anywhere, you may have to add a [Linker.xml entry](https://docs.microsoft.com/en-us/xamarin/cross-platform/deploy-test/linker) or just keep that reference around.

**Comment by deelw** [comment]
Thanks for the info!

**Comment by albertruff** [comment]
One question: How you defined in MLKitVision_ApiDefinitions.cs the GMLImage_MLKitCompatible Extension/Category, that it extends an Interface?

At the Moment, i create Bindings for the new MLKitBarcodeScanning funktionality. For the MLKitBarcodeScanning.framwork, I successfuly created Bindings. But I stuck At this Point in MLKitVision.

P. S.: Thanks @deelw and @mavispuford for your discussion, it helped me a lot.

**Comment by deelw** [comment]
@albertruff for MLKitTextRecognition 1.2.0 it works great, but version 1.3.0 I did also not succeed in making working bindings because of the new GMLImage_MLKitCompatible. I tried several ways including modifying the generated bindings. Maybe @mavispuford has a solution?
I did take a look at the [release notes of MLKit](https://developers.google.com/ml-kit/release-notes) and Google is working on a new version thats in beta MLKitTextRecognition (2) 1.4.0-beta1
So, at this moment you could stay at 1.2.0 or try the beta.

**Comment by albertruff** [comment]
For the MLKitBarcodeScanning, the 1.4.0 is not in beta, it is the relase version and i use them.
For the GMLImage_MLKitCompatible-Problem, I found a working solution but it's not ideal:

- In the MLKitVision ApiDefinition.cs I commented out the interface MLKitCompatible
- Then I build the MLKitVision Project to creat the dll
- After that, I created, for the MLImage, the ApiDefinition.cs and a Binding-Project
- In the MLImage-Binding-Project, I referenced to the MLKitVision.dll
- After that it was possible to implement the IMLKCompatibleImage on the GMLImage
It is the same functionality, that was created in MLKitVision with the MLKitCompatible. The problem is, that in Obj-C it is possible to create an extension for a class to say that this class implements an interface. In C#, I dont found such a possibility.

**Comment by deelw** [comment]
@albertruff 

In C# you can you only have extensions for methods. Another way you could possibly achieve your goal is when you define a class as partial then you can 'extend' that class with an interface definition.

**Comment by deelw** [comment]
@albertruff 
In C# you can only have extensions for methods. Another way to achieve your goal is to define a class as partial, then you can 'extend' that class with an interface definition by defining a partial class with the same name in the same namespace that extends the interface.

**Comment by ElteHupkes** [comment]
I'm a bit late to this party (or [early](https://github.com/xamarin/GoogleApisForiOSComponents/issues/431) depending on how you look at it 😉), but do I understand correctly from the the second comment by @deelw that this repository is essentially no longer maintained?

**Comment by deelw** [comment]
@ElteHupkes thats right. There are some people maintaining the Android part, but at the iOS side there is no maintenance. Th team was dissolved because everybody had to work on Maui.

**Comment by ElteHupkes** [comment]
@deelw Well, that's... annoying. A notice on the front page of the repo would've been nice. Preaching to the choir of course, I'm grateful someone knew and shared it here, thanks.

I must say I've avoided the rabbit hole of creating bindings for iOS so far, but if I get to it this time (and succeed) I might turn it into a NuGet package.

**Comment by BjornVanslembrouck** [comment]
Is anybody able to share the bindings they have. Trying to generate them myself, but it seems to be a bigger nightmare than initially thought. 
Doesn't help that the `sharpie pod` command doesn't work anymore, which makes half of the documentation useless...

**Comment by dmariogatto** [comment]
Hi all,

I've create updated bindings for the following SDKs, at the time of posting this includes,

- [Text Recognition v2](https://developers.google.com/ml-kit/vision/text-recognition/v2/ios)
- [Face Detection](https://developers.google.com/ml-kit/vision/face-detection/ios)
- [Barcode Scanning](https://developers.google.com/ml-kit/vision/barcode-scanning/ios)
- [Image Labeling](https://developers.google.com/ml-kit/vision/image-labeling/ios)
- [Object Detection & Tracking](https://developers.google.com/ml-kit/vision/object-detection/ios)
- [Digital Ink Recognition](https://developers.google.com/ml-kit/vision/digital-ink-recognition/ios)

[MLKit Vision Bindings](https://github.com/dmariogatto/GoogleApisForiOSComponents/tree/firebase-880-mlkitvision/source/MLKit)
[MLKit Vision Sample](https://github.com/dmariogatto/GoogleApisForiOSComponents/tree/firebase-880-mlkitvision/samples/MLKit/MLKitVision/MLKitVisionSample)

I'll probably merge these into branch for #501.

@deelw Could you please reopen this issue? Thanks!

Also tagging #431, as it's a related issue.

**Comment by BjornVanslembrouck** [comment]
@dmariogatto, thanks for this!!

I initially had some issues building the `--targets=externals`, because `Firebase.CloudFirestore` had some issues with generating the SSL package bindings in one of its deeper dependencies. As I don't really need those, I commented them out in the cake files and I could then without issues generate the `nuget` packages.

However, when using them, I can reference all the methods from my project, but when running it on a simulator I keep getting the following error: 
`Could not create an native instance of the type 'MLKit.TextRecognition.LatinTextRecognizerOptions': the native class hasn't been loaded. It is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false`

After some extra digging and comparing with your samples application (which does work), I think the issue lays around the `xamarin.build.download` integrations in the target files. I think it should download these files, but I have the impression it just ignores them which then leads to the error that the native libraries aren't there.

Do you have any idea why these could be ignored when calling it from within a NuGet package? I tried loosening up the conditions on the `<ItemGroup Condition="('$(OutputType)'!='Library' OR '$(IsAppExtension)'=='True')">` that surrounds the `<XamarinBuildDownload Include="$(_GoogleAppMeasurementItemsFolder)">` tag as I thought it had something to do with my project type, but that didn't seem to work either.

**Comment by dmariogatto** [comment]
@BjornVanslembrouck

I haven't had a build error for the SSL package, was it XCode? I assume it was `BoringSSL-GRPC`?

The missing native class definitely sounds like the targets file isn't running. A trick to see if the target is actually executing is to add a `Message` element inside the `Target` ([example](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-targets?view=vs-2022)), it'll display in the build output. I'd double check your iOS [project imports](https://github.com/dmariogatto/GoogleApisForiOSComponents/blob/38811ff97988e3e564d0bed9cd0baab870cc817a/samples/MLKit/MLKitVision/MLKitVisionSample/MLKitVisionSample.csproj#L205) and whether your walking up the correct number of directories.

**Comment by BjornVanslembrouck** [comment]
@dmariogatto, that is what confused me quite a bit TBH. I always assumed that when a `.target` file lives inside the `build` folder inside the NuGet package, it gets added to the project automatically. 
Read a bit more about it and it indeed seems that that is what it should do. There are however some articles mentioning that you need to add the `targets` and `props` files specifically to the `nuspec`, which isn't the case at the moment.
Not sure if adding it to the `nuspec` file is for the old config file approach or for the `packageReference` as well.

I added the following lines to my `.csproj` and it now seems to work as expected:
`	<Import Project="$(NuGetPackageRoot)Xamarin.Firebase.iOS.Core/8.8.0/buildTransitive/Xamarin.Firebase.iOS.Core.targets" />
	<Import Project="$(NuGetPackageRoot)Xamarin.MLKit.iOS.Core/4.0.0/buildTransitive/Xamarin.MLKit.iOS.Core.targets" />
	<Import Project="$(NuGetPackageRoot)xamarin.mlkit.ios.textrecognition/1.0.0/buildTransitive/Xamarin.MLKit.iOS.TextRecognition.targets" />
	<Import Project="$(NuGetPackageRoot)Xamarin.MLKit.iOS.TextRecognition.Latin/1.4.0/buildTransitive/Xamarin.MLKit.iOS.TextRecognitionLatin.targets" />
	<Import Project="$(NuGetPackageRoot)Xamarin.MLKit.iOS.VisionKit/3.0.0/buildTransitive/Xamarin.MLKit.iOS.VisionKit.targets" />`

Thanks for the help!!

**Comment by deelw** [comment]
@dmariogatto for iOS we did switch to Apple Vision for OCR. Would you still want me to reopen this issue?

**Comment by dmariogatto** [comment]
@deelw Thanks for following up. I wouldn't worry about reopening the issue.

**Comment by deelw** [comment]
@dmariogatto I would not reopen this issues unless you request me to. And you did so Nov 21th 2021 by tagging me "@deelw Could you please reopen this issue? Thanks!"
Do you still want me to reopen this issue?

**Comment by dmariogatto** [comment]
@deelw Apologies, I forgot about my previous request. Leave it closed for the moment, it's up to the project maintainers if they want it reopened.
