### ISSUE TITLE
Mobile Ads: Visual Studio -> Unpacking failed.

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/GoogleApisForiOSComponents#58]
When I add the NuGet in VS on Windows and try to build I get:

Unpacking failed. Please download 'https://dl.google.com/dl/cpdc/3605b6f6378a6399-Google-Mobile-Ads-SDK-7.13.0.tar.gz' and extract it to the 'C:\GitHub\app\packages\.xbcache\Gmbladssdk-7.13.0' directory and create an empty file called 'C:\GitHub\app\packages\.xbcache\Gmbladssdk-7.13.0.unpacked'.	

If I follow these steps it works alright, but I shouldn't have to. On XS on Mac it works great (and on build servers).

**Comment by SergeyMNet** [comment]
I have the same error, how I can fix it?

**Comment by SotoiGhost** [comment]
@jamesmontemagno @SergeyMNet 

Sometimes, the download will fail because the download path, plus, the name of tar.gz/.zip hits the Microsoft MAX_PATH limit. Please try these workarounds, if not, let me know to review it.

---

1. As a first step in troubleshooting, attempt to download and extract the files manually as indicated in the error message. Remember to create the empty file listed in the error message.
2. If that still doesn't result in a project that can successfully build, check to ensure the MAX_PATH limit (on Windows only) is not being hit. Try moving the project to the root of the disk.
3. If moving the solution to the root of the disk is not possible or does not solve the issue, the extraction location can be changed through a `.csproj` property. Add the following lines to the app's csproj file (this will cause the files to be extracted to `C:\Code\.xc`):
    * Add to .csproj:
```
<PropertyGroup>
  <XamarinBuildDownloadDir>C:\Code\.xc</XamarinBuildDownloadDir>
</PropertyGroup>
```

4. There is also the possibility that the download file was corrupted and not downloaded correctly. In order to force the task to re-download the file, delete the contents of the cache location. Locations for each platform are:
    * OSX: ~/Library/Caches/XamarinBuildDownload
    * Windows: %localappdata%\XamarinBuildDownloadCache
