### ISSUE TITLE
Firebase Analytics not loading Google Tag Manager Container.

### ISSUE THREAD

**Issue by aphex3k** [xamarin/GoogleApisForiOSComponents#60]
If I run firebase analytics in swift, it produces the following log:

    2017-01-13 11:57:54.248 Seamgen Test[54187:443236] GoogleTagManager info: Loading container: GTM-WMQLF7S

But running the Xamarin sample App I don't see anything alike after I added my Google services plist and container. Also don't see anything logged in GA...

**Comment by JichinThomas** [comment]
We have a related issue for our Xamarin Application, where despite using Firebase Analytics as a the data layer for GTM, and events trigger in Firebase, we dont see them in Google Analytics.

**Comment by SotoiGhost** [comment]
We figured out that GTM is getting stripped by linker, but also, GTM v5.0.6 is not compatible with any current version of Firebase.Analytics. We are working on the update.

**Comment by JichinThomas** [comment]
@SotoiGhost Thanks for acknowledging this as a bug. Is there a broad timeline by which a fix for the GTM Component can be expected? Is the scale of the bug such that a significant fix needs to be implemented or is it possible to patch it up quickly? I ask since one of our app channels is impacted from the lack of analytics coming through in GTM.

**Comment by SotoiGhost** [comment]
@JichinThomas GTM was needed to apply a significant fix to be compatible with Firebase again. The update was accepted and merge into master. By the next days the update will available on NuGet and Store.

**Comment by JichinThomas** [comment]
@SotoiGhost Looks like this 5.0.8 has been released last night with your update. Looking forward to validating the fix to our scenario.
