### ISSUE TITLE
Firebase Crash Reporting: not reporting except when logging prior to crash on iOS

### ISSUE THREAD

**Issue by jderrough** [xamarin/GoogleApisForiOSComponents#76]
Hi,

Firebase Crash Reporting has an odd behaviour on iOS: crashes are only reported if at least one message has been logged prior to a crash. I was able to reproduce it in a minimal project, if that helps.

Basically:
- No crash reported
```
var crash = new NSObject();
crash.PerformSelector (new Selector("doesNotRecognizeSelector"), crash, 0);
```
- Crash reported
```
CrashReporting.Log ("Cause Crash button clicked");

var crash = new NSObject();
crash.PerformSelector (new Selector("doesNotRecognizeSelector"), crash, 0);
```

Is it intended or is that a bug?

Best regards,
Jonathan

**Comment by lassana** [comment]
Same problem.

**Comment by SotoiGhost** [comment]
No, this is a bug. The Crash Reporting bits are being stripped out by the linker. This is happening because (depending on your project settings) the linker finds out that nothing of the Crash Reporting library is being referenced so it decides to remove those binaries to reduce the size of the app. 

So, here is some workaround for this:

1. You need to reference something from the library, like `CrashReporting.Log ("");` to avoid stripping out the library.
2. Open your project settings -> **Build** -> **iOS Build** and type `--linkskip=Firebase.CrashReporting` in **Additional mtouch arguments** textbox. Add this for both **Debug** and **Release** configuration.

I'll release a fix for this. Sorry for the inconveniences.

Greetings,
Israel Soto.
