### ISSUE TITLE
CrashReporting.Log crashes with string containing %

### ISSUE THREAD

**Issue by csoren** [xamarin/GoogleApisForiOSComponents#81]
CrashReporting.Log will crash when given certain strings that contain %. Presumably because the argument is passed on to _FIRCrashLogv as the format string instead of as the argument with a format string of "%s"

_FIRCrashLogv (pMessage, IntPtr.Zero);

in

https://github.com/xamarin/GoogleApisForiOSComponents/blob/master/Firebase.CrashReporting/source/Firebase.CrashReporting/Extension.cs

**Comment by SotoiGhost** [comment]
We added a note in docs that the developer must give an escaped string instead of adding a workaround because it may be difficult to "clean up" unescaped or partially escaped strings where sequences are unpredictable. Also, we decided this because the C function where the string is passed expects an escaped string according to Obj-C headers.

In this case, if you want to print a `%`, you must type `%%` in the string.

Hope this helps you.

Best.
